# Generated by Django 5.1.1 on 2024-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_current_members_room_max_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_members',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
